import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const login = read('src/components/LoginView.jsx');
const auth = read('src/hooks/useAuth.js');
const onboarding = read('src/components/SocialOnboardingView.jsx');
const dashboard = read('src/components/DashboardView.jsx');
const membership = read('src/components/dashboard/CommunityMembershipCard.jsx');
const department = read('src/hooks/useDepartment.js');
const app = read('src/App.jsx');
const actions = read('src/hooks/useUserBibleActions.js');
const header = read('src/components/dashboard/DashboardHeader.jsx');

for (const text of ['카카오로 시작하기', '구글로 시작하기', '기존 회원 로그인 (이름·생년월일로)', '로그인 없이 둘러보기']) assert.match(login, new RegExp(text.replace(/[()·]/g, '\\$&')));
assert.match(login, /교회 관리자 로그인/);
assert.match(login, /소셜 계정이 없어요/);
assert.match(auth, /buildKakaoAuthorizeUrl/);
assert.match(auth, /signInWithCustomToken/);
assert.match(auth, /isValidKakaoState/);
assert.doesNotMatch(auth, /OAuthProvider\('oidc\.kakao'\)/);
assert.match(auth, /openSocialOnboarding\(cred\.user, 'google\.com'\)/);
assert.match(onboarding, /1단계 \/ 3단계/);
assert.match(onboarding, /2단계 \/ 3단계/);
assert.match(onboarding, /3단계 \/ 3단계/);
assert.match(onboarding, /UNAFFILIATED_CHURCH_ID/);
assert.match(auth, /transaction\.set\(rosterRef/);
assert.match(auth, /transaction\.set\(userRef/);
assert.match(dashboard, /내 단체 관리/);
assert.match(membership, /기준으로 보기/);
assert.match(membership, /혼자 읽기 모임으로 돌아가기/);
assert.match(department, /currentUser\.churchId === UNAFFILIATED_CHURCH_ID[\s\S]*Promise\.resolve\(\{ docs: \[\] \}\)/);
assert.match(app, /<DashboardView[\s\S]*?currentUser=\{dashboardUser\}/);
assert.match(app, /currentUser\.accountType === 'personal' && currentUser\.planId[\s\S]*?setView\('dashboard'\)/);
assert.doesNotMatch(app, /currentUser\.accountType === 'personal'[\s\S]{0,160}setView\('personal_community_onboarding'\)/);
assert.doesNotMatch(dashboard, /users[^\n]*\.set\([^\n]*\.\.\.currentUser/);
assert.doesNotMatch(actions, /users[^\n]*\.set\([^\n]*\.\.\.currentUser/);
assert.match(header, /flex flex-wrap items-center gap-1\.5 w-full py-1 md:order-2[^"]*md:flex-nowrap md:justify-end/);
assert.doesNotMatch(header, /overflow-x-auto|scrollbar-hide|justify-between md:justify-end/);
assert.match(header, /hidden h-4 w-px shrink-0 bg-slate-200 md:block/);
console.log('라운드 11 계약 검증 통과: 첫 화면, 소셜, 3단계 온보딩, 소속 관리, roster-only');
